import groovy.json.JsonSlurper
if(hostProps.get('pve.api.insecure')?.toString()?.toBoolean()){def tm=[getAcceptedIssuers:{->[] as java.security.cert.X509Certificate[]},checkClientTrusted:{c,a->},checkServerTrusted:{c,a->}] as javax.net.ssl.X509TrustManager;
def sc=javax.net.ssl.SSLContext.getInstance('TLS');
sc.init(null,[tm] as javax.net.ssl.TrustManager[],new java.security.SecureRandom());
javax.net.ssl.HttpsURLConnection.setDefaultSSLSocketFactory(sc.socketFactory);
javax.net.ssl.HttpsURLConnection.setDefaultHostnameVerifier({h,s->true} as javax.net.ssl.HostnameVerifier)}
def hp = { String k, String d = null ->hostProps.get(k)?:d};
def b=hp('pve.api.url');
def a=hp('pve.api.token');
def t=(hp('pve.api.timeout','10000') as int);
if(!b||!a){System.err.println('Missing pve.api.url or pve.api.token');
return 2};
def g = { String q ->def c=new URL(b.replaceAll('/+$','')+'/api2/json'+q).openConnection();
c.connectTimeout=t;
c.readTimeout=t;
c.setRequestProperty('Authorization','PVEAPIToken='+a);
if(c.responseCode<200||c.responseCode>=300)throw new IOException('HTTP '+c.responseCode);
new JsonSlurper().parse(c.inputStream).data};
try{def n=taskProps.get('pve_node');
if(!n)throw new IOException('Missing instance property pve_node');
def s=g('/nodes/'+n+'/status');
def r=g('/nodes/'+n+'/rrddata?timeframe=hour&cf=AVERAGE');
def x=r?r[-1]:[:];
def m=s.memory?:[:];
def w=s.swap?:[:];
def f=s.rootfs?:[:];
println 'up=1';
println 'cpuPct='+(s.cpu?s.cpu*100:0);
println 'load1='+(s.loadavg?s.loadavg[0]:0);
println 'memUsedPct='+(m.total?m.used*100/m.total:0);
println 'memUsedBytes='+(m.used?:0);
println 'memTotalBytes='+(m.total?:0);
println 'swapUsedPct='+(w.total?w.used*100/w.total:0);
println 'rootUsedPct='+(f.total?f.used*100/f.total:0);
println 'rootUsedBytes='+(f.used?:0);
println 'rootTotalBytes='+(f.total?:0);
println 'uptimeSeconds='+(s.uptime?:0);
println 'netInBytes='+(x.netin?:0);
println 'netOutBytes='+(x.netout?:0);
return 0}catch(e){System.err.println('Proxmox API error: '+e.message);
return 2}
